/*!
* \file   TFEL/Material/FullChabocheMemory.hxx
* \brief  this file implements the FullChabocheMemory Behaviour.
*         File generated by tfel version 4.1.0
* \author Baris Telmen
 */

#ifndef LIB_TFELMATERIAL_FULLCHABOCHEMEMORY_HXX
#define LIB_TFELMATERIAL_FULLCHABOCHEMEMORY_HXX

#include<string>
#include<iostream>
#include<limits>
#include<stdexcept>
#include<algorithm>

#include"TFEL/Raise.hxx"
#include"TFEL/PhysicalConstants.hxx"
#include"TFEL/Config/TFELConfig.hxx"
#include"TFEL/Config/TFELTypes.hxx"
#include"TFEL/TypeTraits/IsFundamentalNumericType.hxx"
#include"TFEL/TypeTraits/IsReal.hxx"
#include"TFEL/Math/General/IEEE754.hxx"
#include"TFEL/Material/MaterialException.hxx"
#include"TFEL/Material/MechanicalBehaviour.hxx"
#include"TFEL/Material/MechanicalBehaviourTraits.hxx"
#include"TFEL/Material/OutOfBoundsPolicy.hxx"
#include"TFEL/Material/BoundsCheck.hxx"
#include"TFEL/Material/IsotropicPlasticity.hxx"
#include"TFEL/Material/Lame.hxx"
#include"TFEL/Material/Hosford1972YieldCriterion.hxx"
#include"MFront/BehaviourProfiler.hxx"
#include"TFEL/Material/FullChabocheMemoryBehaviourData.hxx"
#include"TFEL/Material/FullChabocheMemoryIntegrationData.hxx"

#include"TFEL/Math/Array/ViewsArray.hxx"
#include"TFEL/Math/tvector.hxx"
#include"TFEL/Math/Vector/tvectorIO.hxx"
#include"TFEL/Math/tmatrix.hxx"
#include"TFEL/Math/Matrix/tmatrixIO.hxx"
#include"TFEL/Math/st2tost2.hxx"
#include"TFEL/Math/ST2toST2/ST2toST2ConceptIO.hxx"
#include"TFEL/Math/TinyNewtonRaphsonSolver.hxx"
#include"MFront/Aster/Aster.hxx"

namespace tfel::material{

struct FullChabocheMemoryParametersInitializer
{
static FullChabocheMemoryParametersInitializer&
get();

double theta;
double epsilon;
double minimal_time_step_scaling_factor;
double maximal_time_step_scaling_factor;
double numerical_jacobian_epsilon;
unsigned short iterMax;

void set(const char* const,const double);

void set(const char* const,const unsigned short);

/*!
 * \brief convert a string to double
 * \param[in] p : parameter
 * \param[in] v : value
 */
static double getDouble(const std::string&,const std::string&);
/*!
 * \brief convert a string to unsigned short
 * \param[in] p : parameter
 * \param[in] v : value
 */
static unsigned short getUnsignedShort(const std::string&,const std::string&);
private :

FullChabocheMemoryParametersInitializer();

FullChabocheMemoryParametersInitializer(const FullChabocheMemoryParametersInitializer&);

FullChabocheMemoryParametersInitializer&
operator=(const FullChabocheMemoryParametersInitializer&);
/*!
 * \brief read the parameters from the given file
 * \param[out] pi : parameters initializer
 * \param[in]  fn : file name
 */
static void readParameters(FullChabocheMemoryParametersInitializer&,const char* const);
};

//! \brief forward declaration
template<ModellingHypothesis::Hypothesis, typename NumericType, bool use_qt>
struct FullChabocheMemory;

//! \brief forward declaration
template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType>
std::ostream&
 operator <<(std::ostream&,const FullChabocheMemory<hypothesis, NumericType, false>&);

/*!
 * FullChabocheMemory profiler
 */
struct FullChabocheMemoryProfiler
{
//! return the profiler associated with the behaviour
static mfront::BehaviourProfiler& getProfiler();
}; // end of struct FullChabocheMemoryProfiler

/*!
* \class FullChabocheMemory
* \brief This class implements the FullChabocheMemory behaviour.
* \tparam hypothesis: modelling hypothesis.
* \tparam NumericType: numerical type.
* \author Baris Telmen
* FullChabocheMemory 
*/
template<ModellingHypothesis::Hypothesis hypothesis,typename NumericType>
struct FullChabocheMemory<hypothesis, NumericType, false> final
: public MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>,
public FullChabocheMemoryProfiler,
public FullChabocheMemoryBehaviourData<hypothesis, NumericType, false>,
public FullChabocheMemoryIntegrationData<hypothesis, NumericType, false>,
public tfel::math::TinyNewtonRaphsonSolver<4*ModellingHypothesisToStensorSize<hypothesis>::value+2, NumericType, FullChabocheMemory<hypothesis, NumericType, false>>{

static constexpr unsigned short N = ModellingHypothesisToSpaceDimension<hypothesis>::value;

static_assert(N==1||N==2||N==3);
static_assert(tfel::typetraits::IsFundamentalNumericType<NumericType>::cond);
static_assert(tfel::typetraits::IsReal<NumericType>::cond);

friend std::ostream& operator<< <>(std::ostream&,const FullChabocheMemory&);

friend struct tfel::math::TinyNonLinearSolverBase<4*ModellingHypothesisToStensorSize<hypothesis>::value+2, NumericType, FullChabocheMemory>;
static constexpr unsigned short TVectorSize = N;
typedef tfel::math::StensorDimeToSize<N> StensorDimeToSize;
static constexpr unsigned short StensorSize = StensorDimeToSize::value;
typedef tfel::math::TensorDimeToSize<N> TensorDimeToSize;
static constexpr unsigned short TensorSize = TensorDimeToSize::value;

using ushort =  unsigned short;
using Types = tfel::config::Types<N, NumericType, false>;
using Type = NumericType;
using numeric_type = typename Types::numeric_type;
using real = typename Types::real;
using time = typename Types::time;
using length = typename Types::length;
using frequency = typename Types::frequency;
using speed = typename Types::speed;
using stress = typename Types::stress;
using strain = typename Types::strain;
using strainrate = typename Types::strainrate;
using stressrate = typename Types::stressrate;
using temperature = typename Types::temperature;
using thermalexpansion = typename Types::thermalexpansion;
using thermalconductivity = typename Types::thermalconductivity;
using massdensity = typename Types::massdensity;
using energydensity = typename Types::energydensity;
using TVector = typename Types::TVector;
using DisplacementTVector = typename Types::DisplacementTVector;
using ForceTVector = typename Types::ForceTVector;
using HeatFlux = typename Types::HeatFlux;
using TemperatureGradient = typename Types::TemperatureGradient;
using Stensor = typename Types::Stensor;
using StressStensor = typename Types::StressStensor;
using StressRateStensor = typename Types::StressRateStensor;
using StrainStensor = typename Types::StrainStensor;
using StrainRateStensor = typename Types::StrainRateStensor;
using FrequencyStensor = typename Types::FrequencyStensor;
using Tensor = typename Types::Tensor;
using DeformationGradientTensor = typename Types::DeformationGradientTensor;
using DeformationGradientRateTensor = typename Types::DeformationGradientRateTensor;
using StressTensor = typename Types::StressTensor;
using StiffnessTensor = typename Types::StiffnessTensor;
using Stensor4 = typename Types::Stensor4;
using TangentOperator = StiffnessTensor;
using PhysicalConstants = tfel::PhysicalConstants<NumericType, false>;

public :

typedef FullChabocheMemoryBehaviourData<hypothesis, NumericType, false> BehaviourData;
typedef FullChabocheMemoryIntegrationData<hypothesis, NumericType, false> IntegrationData;
typedef typename MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::SMFlag SMFlag;
typedef typename MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::SMType SMType;
using MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::ELASTIC;
using MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::SECANTOPERATOR;
using MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::TANGENTOPERATOR;
using MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::CONSISTENTTANGENTOPERATOR;
using MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::NOSTIFFNESSREQUESTED;
using MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::STANDARDTANGENTOPERATOR;
using IntegrationResult = typename MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::IntegrationResult;

using MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::SUCCESS;
using MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::FAILURE;
using MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::UNRELIABLE_RESULTS;

using StressFreeExpansionType = StrainStensor;

private :



tfel::math::View<StrainStensor> deel;
#line 30 "FullChabocheMemory.mfront"
real& dp;
#line 32 "FullChabocheMemory.mfront"
tfel::math::ViewsFixedSizeVector<StrainStensor, ushort, 2> da;
#line 33 "FullChabocheMemory.mfront"
real& dq;
#line 34 "FullChabocheMemory.mfront"
tfel::math::View<Stensor> dKsi;

#line 38 "FullChabocheMemory.mfront"
real lambda;
#line 39 "FullChabocheMemory.mfront"
real mu;

NumericType theta;
NumericType epsilon;
real minimal_time_step_scaling_factor;
real maximal_time_step_scaling_factor;
NumericType numerical_jacobian_epsilon;
ushort iterMax;

//! Tangent operator;
TangentOperator Dt;
//! alias to the tangent operator;
TangentOperator& dsig_ddeto;
// updating material properties, in mandatory
void updateMaterialPropertiesDependantOnStateVariables(){
using namespace std;
using namespace tfel::math;
using std::vector;
}

SMType stiffness_matrix_type;
void computeNumericalJacobian(tfel::math::tmatrix<4*StensorSize+2,4*StensorSize+2, NumericType>& njacobian)
{
using namespace std;
using namespace tfel::math;
tvector<4*StensorSize+2, NumericType> tzeros(this->zeros);
tvector<4*StensorSize+2, NumericType> tfzeros(this->fzeros);
tmatrix<4*StensorSize+2,4*StensorSize+2, NumericType> tjacobian(this->jacobian);
for(ushort mfront_idx = 0; mfront_idx != 4*StensorSize+2; ++mfront_idx){
this->zeros(mfront_idx) -= this->numerical_jacobian_epsilon;
this->computeThermodynamicForces();
this->computeFdF(true);
this->zeros = tzeros;
tvector<4*StensorSize+2, NumericType> tfzeros2(this->fzeros);
this->zeros(mfront_idx) += this->numerical_jacobian_epsilon;
this->computeThermodynamicForces();
this->computeFdF(true);
this->fzeros = (this->fzeros-tfzeros2) / (2 * (this->numerical_jacobian_epsilon));
for(ushort mfront_idx2 = 0; mfront_idx2!= 4*StensorSize+2; ++mfront_idx2){
njacobian(mfront_idx2,mfront_idx) = this->fzeros(mfront_idx2);
}
this->zeros    = tzeros;
this->fzeros   = tfzeros;
}
if(&njacobian!=&(this->jacobian)){
this->jacobian = tjacobian;
}
}

[[nodiscard]] bool
computePartialJacobianInvert(const tfel::math::TinyPermutation<4*StensorSize+2>& jacobian_permutation, tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_eel)
{
using namespace tfel::math;
for(ushort mfront_idx=0; mfront_idx !=StensorSize; ++mfront_idx){
tvector<4*StensorSize+2, NumericType> vect_e(NumericType(0));
vect_e(mfront_idx) = NumericType(1);
if(!TinyMatrixSolve<4*StensorSize+2, NumericType, false>::back_substitute(this->jacobian, jacobian_permutation, vect_e)){
return false;
}
for(ushort mfront_idx2=0; mfront_idx2!=StensorSize; ++mfront_idx2){
partial_jacobian_eel(mfront_idx2,mfront_idx)=vect_e(mfront_idx2);
}
}
return true;
}

[[nodiscard]] bool
computePartialJacobianInvert(const tfel::math::TinyPermutation<4*StensorSize+2>& jacobian_permutation, tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_eel,
tfel::math::derivative_type<real, StrainStensor>& partial_jacobian_p)
{
using namespace tfel::math;
for(ushort mfront_idx=0; mfront_idx !=StensorSize; ++mfront_idx){
tvector<4*StensorSize+2, NumericType> vect_e(NumericType(0));
vect_e(mfront_idx) = NumericType(1);
if(!TinyMatrixSolve<4*StensorSize+2, NumericType, false>::back_substitute(this->jacobian, jacobian_permutation, vect_e)){
return false;
}
for(ushort mfront_idx2=0; mfront_idx2!=StensorSize; ++mfront_idx2){
partial_jacobian_eel(mfront_idx2,mfront_idx)=vect_e(mfront_idx2);
}
partial_jacobian_p(mfront_idx)=vect_e(StensorSize);
}
return true;
}

[[nodiscard]] bool
computePartialJacobianInvert(const tfel::math::TinyPermutation<4*StensorSize+2>& jacobian_permutation, tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_eel,
tfel::math::derivative_type<real, StrainStensor>& partial_jacobian_p,
tfel::math::tvector<2, tfel::math::derivative_type<StrainStensor, StrainStensor>>& partial_jacobian_a)
{
using namespace tfel::math;
for(ushort mfront_idx=0; mfront_idx !=StensorSize; ++mfront_idx){
tvector<4*StensorSize+2, NumericType> vect_e(NumericType(0));
vect_e(mfront_idx) = NumericType(1);
if(!TinyMatrixSolve<4*StensorSize+2, NumericType, false>::back_substitute(this->jacobian, jacobian_permutation, vect_e)){
return false;
}
for(ushort mfront_idx2=0; mfront_idx2!=StensorSize; ++mfront_idx2){
partial_jacobian_eel(mfront_idx2,mfront_idx)=vect_e(mfront_idx2);
}
partial_jacobian_p(mfront_idx)=vect_e(StensorSize);
for(ushort mfront_idx2=0; mfront_idx2!=2; ++mfront_idx2){
for(ushort mfront_idx3=0; mfront_idx3!= StensorSize; ++mfront_idx3){
partial_jacobian_a(mfront_idx2)(mfront_idx3,mfront_idx) = vect_e(StensorSize+1+ mfront_idx3 + mfront_idx2 * StensorSize);
}
}
}
return true;
}

[[nodiscard]] bool
computePartialJacobianInvert(const tfel::math::TinyPermutation<4*StensorSize+2>& jacobian_permutation, tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_eel,
tfel::math::derivative_type<real, StrainStensor>& partial_jacobian_p,
tfel::math::tvector<2, tfel::math::derivative_type<StrainStensor, StrainStensor>>& partial_jacobian_a,
tfel::math::derivative_type<real, StrainStensor>& partial_jacobian_q)
{
using namespace tfel::math;
for(ushort mfront_idx=0; mfront_idx !=StensorSize; ++mfront_idx){
tvector<4*StensorSize+2, NumericType> vect_e(NumericType(0));
vect_e(mfront_idx) = NumericType(1);
if(!TinyMatrixSolve<4*StensorSize+2, NumericType, false>::back_substitute(this->jacobian, jacobian_permutation, vect_e)){
return false;
}
for(ushort mfront_idx2=0; mfront_idx2!=StensorSize; ++mfront_idx2){
partial_jacobian_eel(mfront_idx2,mfront_idx)=vect_e(mfront_idx2);
}
partial_jacobian_p(mfront_idx)=vect_e(StensorSize);
for(ushort mfront_idx2=0; mfront_idx2!=2; ++mfront_idx2){
for(ushort mfront_idx3=0; mfront_idx3!= StensorSize; ++mfront_idx3){
partial_jacobian_a(mfront_idx2)(mfront_idx3,mfront_idx) = vect_e(StensorSize+1+ mfront_idx3 + mfront_idx2 * StensorSize);
}
}
partial_jacobian_q(mfront_idx)=vect_e(3*StensorSize+1);
}
return true;
}

[[nodiscard]] bool
computePartialJacobianInvert(const tfel::math::TinyPermutation<4*StensorSize+2>& jacobian_permutation, tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_eel,
tfel::math::derivative_type<real, StrainStensor>& partial_jacobian_p,
tfel::math::tvector<2, tfel::math::derivative_type<StrainStensor, StrainStensor>>& partial_jacobian_a,
tfel::math::derivative_type<real, StrainStensor>& partial_jacobian_q,
tfel::math::derivative_type<Stensor, StrainStensor>& partial_jacobian_Ksi)
{
using namespace tfel::math;
for(ushort mfront_idx=0; mfront_idx !=StensorSize; ++mfront_idx){
tvector<4*StensorSize+2, NumericType> vect_e(NumericType(0));
vect_e(mfront_idx) = NumericType(1);
if(!TinyMatrixSolve<4*StensorSize+2, NumericType, false>::back_substitute(this->jacobian, jacobian_permutation, vect_e)){
return false;
}
for(ushort mfront_idx2=0; mfront_idx2!=StensorSize; ++mfront_idx2){
partial_jacobian_eel(mfront_idx2,mfront_idx)=vect_e(mfront_idx2);
}
partial_jacobian_p(mfront_idx)=vect_e(StensorSize);
for(ushort mfront_idx2=0; mfront_idx2!=2; ++mfront_idx2){
for(ushort mfront_idx3=0; mfront_idx3!= StensorSize; ++mfront_idx3){
partial_jacobian_a(mfront_idx2)(mfront_idx3,mfront_idx) = vect_e(StensorSize+1+ mfront_idx3 + mfront_idx2 * StensorSize);
}
}
partial_jacobian_q(mfront_idx)=vect_e(3*StensorSize+1);
for(ushort mfront_idx2=3*StensorSize+2; mfront_idx2!=4*StensorSize+2; ++mfront_idx2){
partial_jacobian_Ksi(mfront_idx2,mfront_idx)=vect_e(mfront_idx2);
}
}
return true;
}

void computeThermodynamicForces(){
using namespace std;
using namespace tfel::math;
using std::vector;
{
mfront::BehaviourProfiler::Timer mfront_local_timer(FullChabocheMemoryProfiler::getProfiler(),mfront::BehaviourProfiler::COMPUTETHERMODYNAMICFORCES);
#line 47 "FullChabocheMemory.mfront"
this->sig = this->lambda * trace((this->eel+(this->theta)*(this->deel))) * Stensor::Id() + 2 * this->mu * (this->eel+(this->theta)*(this->deel));}

} // end of FullChabocheMemory::computeThermodynamicForces

void computeFinalThermodynamicForces(){
using namespace std;
using namespace tfel::math;
using std::vector;
{
mfront::BehaviourProfiler::Timer mfront_local_timer(FullChabocheMemoryProfiler::getProfiler(),mfront::BehaviourProfiler::COMPUTEFINALTHERMODYNAMICFORCES);
#line 47 "FullChabocheMemory.mfront"
this->sig = this->lambda * trace(this->eel) * Stensor::Id() + 2 * this->mu * this->eel;}

} // end of FullChabocheMemory::computeFinalThermodynamicForces

/*!
* \brief Update internal variables at end of integration
*/
void updateIntegrationVariables(){
}

/*!
* \brief Update internal variables at end of integration
*/
void updateStateVariables(){
this->eel += this->deel;
this->p += this->dp;
this->a += this->da;
this->q += this->dq;
this->Ksi += this->dKsi;
}

/*!
* \brief Update auxiliary state variables at end of integration
*/
void updateAuxiliaryStateVariables(){
using namespace std;
using namespace tfel::math;
{
mfront::BehaviourProfiler::Timer mfront_local_timer(FullChabocheMemoryProfiler::getProfiler(),mfront::BehaviourProfiler::UPDATEAUXILIARYSTATEVARIABLES);
#line 103 "FullChabocheMemory.mfront"
const real q_ = this->q - (1 - theta) * this->dq;
#line 104 "FullChabocheMemory.mfront"
const real Q = this->Q0 + (this->Qm - this->Q0) * (1 - exp(-2 * this->Mu * q_));
#line 105 "FullChabocheMemory.mfront"
this->R += this->b * (Q - this->R) * this->dp;}

}

//! \brief Default constructor (disabled)
FullChabocheMemory() =delete ;
//! \brief Copy constructor (disabled)
FullChabocheMemory(const FullChabocheMemory&) = delete;
//! \brief Assignement operator (disabled)
FullChabocheMemory& operator = (const FullChabocheMemory&) = delete;

public:

/*!
* \brief Constructor
*/
FullChabocheMemory(const FullChabocheMemoryBehaviourData<hypothesis, NumericType, false>& src1,
const FullChabocheMemoryIntegrationData<hypothesis, NumericType, false>& src2)
: FullChabocheMemoryBehaviourData<hypothesis, NumericType, false>(src1),
FullChabocheMemoryIntegrationData<hypothesis, NumericType, false>(src2),
deel(tfel::math::map<StrainStensor, 0>(this->zeros)),
dp(this->zeros(StensorSize)),
da(tfel::math::map<2, StrainStensor, StensorSize+1>(this->zeros)),
dq(this->zeros(3*StensorSize+1)),
dKsi(tfel::math::map<Stensor, 3*StensorSize+2>(this->zeros)),
dsig_ddeto(Dt)
{
using namespace std;
using namespace tfel::math;
using std::vector;
this->theta = FullChabocheMemoryParametersInitializer::get().theta;
this->epsilon = FullChabocheMemoryParametersInitializer::get().epsilon;
this->minimal_time_step_scaling_factor = FullChabocheMemoryParametersInitializer::get().minimal_time_step_scaling_factor;
this->maximal_time_step_scaling_factor = FullChabocheMemoryParametersInitializer::get().maximal_time_step_scaling_factor;
this->numerical_jacobian_epsilon = FullChabocheMemoryParametersInitializer::get().numerical_jacobian_epsilon;
this->iterMax = FullChabocheMemoryParametersInitializer::get().iterMax;
}

/*
 * \brief constructor for the Aster interface
 * \param[in] ASTERdt_: time increment
 * \param[in] ASTERT_: temperature
 * \param[in] ASTERdT_: temperature increment
 * \param[in] ASTERmat: material properties
 * \param[in] ASTERint_vars: state variables
 * \param[in] ASTERext_vars: external state variables
 * \param[in] ASTERdext_vars: external state variables increments
 */
FullChabocheMemory(const NumericType* const ASTERdt_,
const NumericType* const ASTERT_,
const NumericType* const ASTERdT_,
const NumericType* const ASTERmat,
const NumericType* const ASTERint_vars,
const NumericType* const ASTERext_vars,
const NumericType* const ASTERdext_vars)
: FullChabocheMemoryBehaviourData<hypothesis, NumericType,false>(ASTERT_,ASTERmat,
ASTERint_vars,ASTERext_vars),
FullChabocheMemoryIntegrationData<hypothesis, NumericType,false>(ASTERdt_,ASTERdT_,ASTERdext_vars),
deel(tfel::math::map<StrainStensor, 0>(this->zeros)),
dp(this->zeros(StensorSize)),
da(tfel::math::map<2, StrainStensor, StensorSize+1>(this->zeros)),
dq(this->zeros(3*StensorSize+1)),
dKsi(tfel::math::map<Stensor, 3*StensorSize+2>(this->zeros)),
dsig_ddeto(Dt)
{
using namespace std;
using namespace tfel::math;
using std::vector;
this->theta = FullChabocheMemoryParametersInitializer::get().theta;
this->epsilon = FullChabocheMemoryParametersInitializer::get().epsilon;
this->minimal_time_step_scaling_factor = FullChabocheMemoryParametersInitializer::get().minimal_time_step_scaling_factor;
this->maximal_time_step_scaling_factor = FullChabocheMemoryParametersInitializer::get().maximal_time_step_scaling_factor;
this->numerical_jacobian_epsilon = FullChabocheMemoryParametersInitializer::get().numerical_jacobian_epsilon;
this->iterMax = FullChabocheMemoryParametersInitializer::get().iterMax;
}

/*!
 * \ brief initialize the behaviour with user code
 */
[[nodiscard]] bool initialize(){
using namespace std;
using namespace tfel::math;
using std::vector;
{
mfront::BehaviourProfiler::Timer mfront_local_timer_init(FullChabocheMemoryProfiler::getProfiler(),mfront::BehaviourProfiler::INITIALIZELOCALVARIABLES);
#line 42 "FullChabocheMemory.mfront"
this->lambda = computeLambda(this->young, this->nu);
#line 43 "FullChabocheMemory.mfront"
this->mu = computeMu(this->young, this->nu);
}
return true;
}

/*!
 * \brief set the policy for "out of bounds" conditions
 */
void
setOutOfBoundsPolicy(const OutOfBoundsPolicy policy_value){
  this->policy = policy_value;
} // end of setOutOfBoundsPolicy

/*!
* \return the modelling hypothesis
*/
constexpr ModellingHypothesis::Hypothesis
getModellingHypothesis() const{
return hypothesis;
} // end of getModellingHypothesis

//! \brief check physical bounds and standard bounds
void checkBounds() const{
} // end of checkBounds

[[nodiscard]] IntegrationResult computePredictionOperator(const SMFlag,const SMType) override{
tfel::raise("FullChabocheMemory::computePredictionOperator: "
"unsupported prediction operator flag");
}

real getMinimalTimeStepScalingFactor() const noexcept override{
  return this->minimal_time_step_scaling_factor;
}

std::pair<bool, real>
computeAPrioriTimeStepScalingFactor(const real current_time_step_scaling_factor) const override{
const auto time_scaling_factor = this->computeAPrioriTimeStepScalingFactorII();
return {time_scaling_factor.first,
        std::min(std::min(std::max(time_scaling_factor.second,
                                   this->minimal_time_step_scaling_factor),
                          this->maximal_time_step_scaling_factor),
                  current_time_step_scaling_factor)};
}

/*!
 * \brief Integrate behaviour law over the time step
 */
[[nodiscard]] IntegrationResult integrate(const SMFlag smflag,const SMType smt) override{
using namespace std;
using namespace tfel::math;
this->stiffness_matrix_type = smt;
tfel::raise_if(smflag!=MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::STANDARDTANGENTOPERATOR,
"invalid tangent operator flag");
{
mfront::BehaviourProfiler::Timer mfront_local_timer(FullChabocheMemoryProfiler::getProfiler(),mfront::BehaviourProfiler::INTEGRATOR);
tfel::math::TinyNewtonRaphsonSolver<4*ModellingHypothesisToStensorSize<hypothesis>::value+2, NumericType, FullChabocheMemory<hypothesis, NumericType, false>>::epsilon = this->epsilon;
tfel::math::TinyNewtonRaphsonSolver<4*ModellingHypothesisToStensorSize<hypothesis>::value+2, NumericType, FullChabocheMemory<hypothesis, NumericType, false>>::iterMax = this->iterMax;
if(!this->solveNonLinearSystem()){
return MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::FAILURE;
}
if (this->stiffness_matrix_type != NOSTIFFNESSREQUESTED){
this->updateOrCheckJacobian();
}
}
this->updateIntegrationVariables();
this->updateStateVariables();
this->computeFinalThermodynamicForces();
this->updateAuxiliaryStateVariables();
if(smt!=NOSTIFFNESSREQUESTED){
if(!this->computeConsistentTangentOperator(smt)){
return MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::FAILURE;
}
}
return MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::SUCCESS;
} // end of FullChabocheMemory::integrate

bool computeResidual(){
this->computeThermodynamicForces();
return this->computeFdF(false);
}
//! \return the norm of the residual
NumericType computeResidualNorm() {
return tfel::math::norm(this->fzeros) / (4*StensorSize+2);
}
/*!
 * \brief check the convergence of the method
 * \param[in] error: current error
 */
bool checkConvergence(const NumericType error) {
auto converged = error < this->epsilon;
return converged;
}
/*!
 * \brief update the jacobian matrix if required.
 * \param[in] converged: boolean stating if the method is
 * called after the convergence of the algorithm or before
 * the computation of the next correction.
 *
 * This method can be used to compute the jacobian or part
 * of the jacobian numerically. If the jacobian was computed
 * in `computeResidual`, this method can be used to compare it
 * to a numerical approximation.
 */
void updateOrCheckJacobian(){
this->computeNumericalJacobian(this->jacobian);
}
/*!
 * \brief method meant to set bounds on some components
 * of the current Newton correction or to implement a line
 * search.
 */
void processNewCorrection()
{
}
/*!
 * \brief method meant to process the new estimate.
 *
 * This method may be called to apply bounds on the
 * new estimate and update material properties
 * dependending on the current state.
 */
void processNewEstimate(){
this->updateMaterialPropertiesDependantOnStateVariables();
}
/*!
 * \brief solve linear system
 * \return true on success
 * \param[in] m: matrix
 * \param[in,out] v: right hand side on input, solution on output
 */
bool solveLinearSystem(tfel::math::tmatrix<4*StensorSize+2, 4*StensorSize+2, NumericType>& mfront_matrix,tfel::math::tvector<4*StensorSize+2, NumericType>& mfront_vector)const noexcept{
auto mfront_success = true;
{
mfront::BehaviourProfiler::Timer mfront_local_timer_lu(FullChabocheMemoryProfiler::getProfiler(),mfront::BehaviourProfiler::TINYMATRIXSOLVE);
mfront_success = tfel::math::TinyNewtonRaphsonSolver<4*ModellingHypothesisToStensorSize<hypothesis>::value+2, NumericType, FullChabocheMemory<hypothesis, NumericType, false>>::solveLinearSystem(mfront_matrix, mfront_vector);
}
return mfront_success;
}
/*!
* \brief compute fzeros and jacobian
*/
bool computeFdF(const bool perturbatedSystemEvaluation){
using namespace std;
using namespace tfel::math;
using std::vector;
mfront::BehaviourProfiler::Timer mfront_local_timer(FullChabocheMemoryProfiler::getProfiler(),mfront::BehaviourProfiler::COMPUTEFDF);
// silent compiler warning
static_cast<void>(perturbatedSystemEvaluation); 
constexpr auto eel_offset = 0;
constexpr auto p_offset = StensorSize;
constexpr auto a_offset = StensorSize+1;
constexpr auto q_offset = 3*StensorSize+1;
constexpr auto Ksi_offset = 3*StensorSize+2;
auto feel = tfel::math::map<StrainStensor, 0>(this->fzeros);
real& fp(this->fzeros(StensorSize));
auto fa = tfel::math::map<2, StrainStensor, StensorSize+1>(this->fzeros);
real& fq(this->fzeros(3*StensorSize+1));
auto fKsi = tfel::math::map<Stensor, 3*StensorSize+2>(this->fzeros);
// setting f values to zeros
this->fzeros = this->zeros;
#line 51 "FullChabocheMemory.mfront"
Stensor n = Stensor(0.);
#line 52 "FullChabocheMemory.mfront"
StrainStensor a_[2];
#line 53 "FullChabocheMemory.mfront"
Stensor X_[2];
#line 54 "FullChabocheMemory.mfront"
real g_[2];
#line 55 "FullChabocheMemory.mfront"
StressStensor scin = (this->sig);
#line 56 "FullChabocheMemory.mfront"
const strain p_ = ((this->p) + theta * (this->dp));
#line 57 "FullChabocheMemory.mfront"
for ( unsigned int i=0; i != 2; ++i){
#line 58 "FullChabocheMemory.mfront"
a_[i] = (this->a)[i]+theta*(this->da)[i];
#line 59 "FullChabocheMemory.mfront"
X_[i] = 2.0 * (this->C)[i] * a_[i] / 3.0;
#line 60 "FullChabocheMemory.mfront"
g_[i] = (this->g)[i] * ((this->ainf) + (1.0 - (this->ainf)) * exp(-(this->b) * p_));
#line 61 "FullChabocheMemory.mfront"
scin -= X_[i];
#line 62 "FullChabocheMemory.mfront"
}
#line 63 "FullChabocheMemory.mfront"
const real seq = sigmaeq(scin);
#line 64 "FullChabocheMemory.mfront"
const real Q_ = (this->Q0) + ((this->Qm) - (this->Q0)) * (1 - exp(-2 * (this->Mu) * ((this->q) + theta * (this->dq))));
#line 65 "FullChabocheMemory.mfront"
const stress Rp = (this->R_0) + (this->R) + (this->b) * (Q_ - (this->R)) * (this->dp);
#line 66 "FullChabocheMemory.mfront"
const real F = seq - Rp;
#line 67 "FullChabocheMemory.mfront"
real vp = 0.;
#line 69 "FullChabocheMemory.mfront"
if (F > 0) {
#line 70 "FullChabocheMemory.mfront"
vp = (this->dt) * pow(F/(this->K), (this->m));
#line 71 "FullChabocheMemory.mfront"
n = sqrt(1.5) * deviator(scin) / seq;
#line 72 "FullChabocheMemory.mfront"
real an[2];
#line 74 "FullChabocheMemory.mfront"
for (unsigned int i=0; i != 2; ++i){
#line 75 "FullChabocheMemory.mfront"
an[i] = a_[i] | n;
#line 76 "FullChabocheMemory.mfront"
}
#line 78 "FullChabocheMemory.mfront"
feel += vp * sqrt(1.5) * n - (this->deto);
#line 79 "FullChabocheMemory.mfront"
fp -= vp;
#line 81 "FullChabocheMemory.mfront"
for (unsigned int i = 0; i != 2; ++i){
#line 82 "FullChabocheMemory.mfront"
fa[i] = (this->da)[i] - vp * sqrt(1.5) * n +
#line 83 "FullChabocheMemory.mfront"
g_[i] * vp * ((this->delta)[i] * a_[i] + (1 - (this->delta)[i]) * an[i] * n);
#line 84 "FullChabocheMemory.mfront"
}
#line 86 "FullChabocheMemory.mfront"
Stensor epsplastic = (this->eto) - (this->eel) + vp * sqrt(1.5) * n - (this->Ksi);
#line 87 "FullChabocheMemory.mfront"
real epsplasticeq = sigmaeq(epsplastic);
#line 88 "FullChabocheMemory.mfront"
real Fisot = 2.0 * epsplasticeq / 3.0 - (this->q);
#line 90 "FullChabocheMemory.mfront"
if (Fisot > 0) {
#line 91 "FullChabocheMemory.mfront"
epsplastic = (this->eto) - (this->eel) + vp * sqrt(1.5) * n - (this->Ksi) - theta * (this->dKsi);
#line 92 "FullChabocheMemory.mfront"
epsplasticeq = sigmaeq(epsplastic);
#line 93 "FullChabocheMemory.mfront"
fq = 2.0* epsplasticeq / 3.0 - ((this->q) + theta * (this->dq));
#line 94 "FullChabocheMemory.mfront"
Stensor nstar = 1.5 * epsplastic / epsplasticeq;
#line 95 "FullChabocheMemory.mfront"
fKsi = (this->dKsi) - (1 - (this->Eta)) / (this->Eta) * (this->dq) * nstar;
#line 96 "FullChabocheMemory.mfront"
}
#line 97 "FullChabocheMemory.mfront"
} else {
#line 98 "FullChabocheMemory.mfront"
feel -= (this->deto);
#line 99 "FullChabocheMemory.mfront"
}
static_cast<void>(eel_offset);
static_cast<void>(p_offset);
static_cast<void>(a_offset);
static_cast<void>(q_offset);
static_cast<void>(Ksi_offset);
return true;
}

std::pair<bool, real>
computeAPosterioriTimeStepScalingFactor(const real current_time_step_scaling_factor) const override{
const auto time_scaling_factor = this->computeAPosterioriTimeStepScalingFactorII();
return {time_scaling_factor.first,
        std::min(std::min(std::max(time_scaling_factor.second,
                                   this->minimal_time_step_scaling_factor),
                          this->maximal_time_step_scaling_factor),
                 current_time_step_scaling_factor)};
}

/*!
* \brief Update the internal energy at end of the time step
* \param[in] Psi_s: internal energy at end of the time step
*/
void computeInternalEnergy(stress& Psi_s) const
{
Psi_s=stress{0};
}

/*!
* \brief Update the dissipated energy at end of the time step
* \param[in] Psi_d: dissipated energy at end of the time step
*/
void computeDissipatedEnergy(stress& Psi_d) const
{
Psi_d=stress{0};
}

bool computeConsistentTangentOperator(const SMType smt){
using namespace std;
using namespace tfel::math;
using std::vector;
auto mfront_success = true;
TinyPermutation<4*StensorSize+2> jacobian_permutation;
if(!TinyMatrixSolve<4*StensorSize+2, NumericType, false>::decomp(this->jacobian,jacobian_permutation)){
return false;
}
struct TFEL_VISIBILITY_LOCAL GetPartialJacobianInvert{
GetPartialJacobianInvert(FullChabocheMemory& mfront_behaviour_argument,
const tfel::math::TinyPermutation<4*StensorSize+2>& mfront_permutation_argument,
bool& mfront_success_argument)
: mfront_get_partial_jacobian_invert_behaviour(mfront_behaviour_argument),
mfront_get_partial_jacobian_invert_permutation(mfront_permutation_argument),
mfront_success_reference(mfront_success_argument){}
void operator()(tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_eel){
if(!this->mfront_get_partial_jacobian_invert_behaviour.computePartialJacobianInvert(this->mfront_get_partial_jacobian_invert_permutation, partial_jacobian_eel)){
this->mfront_success_reference = false;
}
}
void operator()(tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_eel,
tfel::math::derivative_type<real, StrainStensor>& partial_jacobian_p){
if(!this->mfront_get_partial_jacobian_invert_behaviour.computePartialJacobianInvert(this->mfront_get_partial_jacobian_invert_permutation, partial_jacobian_eel,
partial_jacobian_p)){
this->mfront_success_reference = false;
}
}
void operator()(tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_eel,
tfel::math::derivative_type<real, StrainStensor>& partial_jacobian_p,
tfel::math::tvector<2, tfel::math::derivative_type<StrainStensor, StrainStensor>>& partial_jacobian_a){
if(!this->mfront_get_partial_jacobian_invert_behaviour.computePartialJacobianInvert(this->mfront_get_partial_jacobian_invert_permutation, partial_jacobian_eel,
partial_jacobian_p,
partial_jacobian_a)){
this->mfront_success_reference = false;
}
}
void operator()(tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_eel,
tfel::math::derivative_type<real, StrainStensor>& partial_jacobian_p,
tfel::math::tvector<2, tfel::math::derivative_type<StrainStensor, StrainStensor>>& partial_jacobian_a,
tfel::math::derivative_type<real, StrainStensor>& partial_jacobian_q){
if(!this->mfront_get_partial_jacobian_invert_behaviour.computePartialJacobianInvert(this->mfront_get_partial_jacobian_invert_permutation, partial_jacobian_eel,
partial_jacobian_p,
partial_jacobian_a,
partial_jacobian_q)){
this->mfront_success_reference = false;
}
}
void operator()(tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_eel,
tfel::math::derivative_type<real, StrainStensor>& partial_jacobian_p,
tfel::math::tvector<2, tfel::math::derivative_type<StrainStensor, StrainStensor>>& partial_jacobian_a,
tfel::math::derivative_type<real, StrainStensor>& partial_jacobian_q,
tfel::math::derivative_type<Stensor, StrainStensor>& partial_jacobian_Ksi){
if(!this->mfront_get_partial_jacobian_invert_behaviour.computePartialJacobianInvert(this->mfront_get_partial_jacobian_invert_permutation, partial_jacobian_eel,
partial_jacobian_p,
partial_jacobian_a,
partial_jacobian_q,
partial_jacobian_Ksi)){
this->mfront_success_reference = false;
}
}
private:
FullChabocheMemory& mfront_get_partial_jacobian_invert_behaviour;
const tfel::math::TinyPermutation<4*StensorSize+2>& mfront_get_partial_jacobian_invert_permutation;
bool& mfront_success_reference;
}; // end of struct GetPartialJacobianInvert
GetPartialJacobianInvert getPartialJacobianInvert(*this, jacobian_permutation, mfront_success);
{
mfront::BehaviourProfiler::Timer mfront_local_timer(FullChabocheMemoryProfiler::getProfiler(),mfront::BehaviourProfiler::COMPUTETANGENTOPERATOR);
#line 109 "FullChabocheMemory.mfront"
StiffnessTensor De;
#line 110 "FullChabocheMemory.mfront"
Stensor4 Je;
#line 111 "FullChabocheMemory.mfront"
computeElasticStiffness<N, Type>::exe(De, (this->lambda), (this->mu));
#line 112 "FullChabocheMemory.mfront"
getPartialJacobianInvert(Je);
#line 113 "FullChabocheMemory.mfront"
(this->Dt) = De * Je;}

return mfront_success;
}

/*!
* \brief compute the sound velocity
* \param[in] rho_m0: mass density in the reference configuration
*/
speed computeSpeedOfSound(const massdensity&) const {
return speed(0);

}

const TangentOperator& getTangentOperator() const{
return this->Dt;
}

void updateExternalStateVariables(){
this->eto  += this->deto;
this->T += this->dT;
}

//!
~FullChabocheMemory()
 override = default;

private:

std::pair<bool, real> computeAPrioriTimeStepScalingFactorII() const{
return {true, this->maximal_time_step_scaling_factor};
}

std::pair<bool, real> computeAPosterioriTimeStepScalingFactorII() const{
return {true,this->maximal_time_step_scaling_factor};
}

//! policy for treating out of bounds conditions
OutOfBoundsPolicy policy = tfel::material::None;

}; // end of FullChabocheMemory class

template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType>
std::ostream&
operator <<(std::ostream& os,const FullChabocheMemory<hypothesis, NumericType, false>& b)
{
os << "εᵗᵒ : " << b.eto << '\n';
os << "Δεᵗᵒ : " << b.deto << '\n';
os << "σ : " << b.sig << '\n';
os << "Δt : " << b.dt << '\n';
os << "young : " << b.young << '\n';
os << "nu : " << b.nu << '\n';
os << "R_0 : " << b.R_0 << '\n';
os << "C : " << b.C << '\n';
os << "g : " << b.g << '\n';
os << "ainf : " << b.ainf << '\n';
os << "b : " << b.b << '\n';
os << "m : " << b.m << '\n';
os << "K : " << b.K << '\n';
os << "Eta : " << b.Eta << '\n';
os << "Qm : " << b.Qm << '\n';
os << "Q0 : " << b.Q0 << '\n';
os << "Mu : " << b.Mu << '\n';
os << "delta : " << b.delta << '\n';
os << "εᵉˡ : " << b.eel << '\n';
os << "Δεᵉˡ : " << b.deel << '\n';
os << "p : " << b.p << '\n';
os << "Δp : " << b.dp << '\n';
os << "a : " << b.a << '\n';
os << "Δa : " << b.da << '\n';
os << "q : " << b.q << '\n';
os << "Δq : " << b.dq << '\n';
os << "Ksi : " << b.Ksi << '\n';
os << "ΔKsi : " << b.dKsi << '\n';
os << "R : " << b.R << '\n';
os << "T : " << b.T << '\n';
os << "ΔT : " << b.dT << '\n';
os << "θ : " << b.theta << '\n';
os << "ε : " << b.epsilon << '\n';
os << "minimal_time_step_scaling_factor : " << b.minimal_time_step_scaling_factor << '\n';
os << "maximal_time_step_scaling_factor : " << b.maximal_time_step_scaling_factor << '\n';
os << "numerical_jacobian_epsilon : " << b.numerical_jacobian_epsilon << '\n';
os << "iterMax : " << b.iterMax << '\n';
return os;
}

/*!
* Partial specialisation for FullChabocheMemory.
*/
template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType>
class MechanicalBehaviourTraits<FullChabocheMemory<hypothesis, NumericType, false> >
{
using size_type = unsigned short;
static constexpr unsigned short N = ModellingHypothesisToSpaceDimension<hypothesis>::value;
static constexpr unsigned short TVectorSize = N;
typedef tfel::math::StensorDimeToSize<N> StensorDimeToSize;
static constexpr unsigned short StensorSize = StensorDimeToSize::value;
typedef tfel::math::TensorDimeToSize<N> TensorDimeToSize;
static constexpr unsigned short TensorSize = TensorDimeToSize::value;
public:
static constexpr bool is_defined = true;
static constexpr bool use_quantities = false;
static constexpr bool hasStressFreeExpansion = false;
static constexpr bool handlesThermalExpansion = false;
static constexpr unsigned short dimension = N;
static constexpr size_type material_properties_nb = 17;
static constexpr size_type internal_variables_nb  = 4*StensorSize+3;
static constexpr size_type external_variables_nb  = 1;
static constexpr size_type external_variables_nb2 = 0;
static constexpr bool hasConsistentTangentOperator = true;
static constexpr bool isConsistentTangentOperatorSymmetric = false;
static constexpr bool hasPredictionOperator = false;
static constexpr bool hasAPrioriTimeStepScalingFactor = false;
static constexpr bool hasComputeInternalEnergy = false;
static constexpr bool hasComputeDissipatedEnergy = false;
/*!
* \return the name of the class.
*/
static const char* getName(){
return "FullChabocheMemory";
}

};

/*!
* Partial specialisation for FullChabocheMemory.
*/
template<typename NumericType>
class MechanicalBehaviourTraits<FullChabocheMemory<ModellingHypothesis::AXISYMMETRICALGENERALISEDPLANESTRESS, NumericType, false> >
{
using size_type = unsigned short;
public:
static constexpr bool is_defined = false;
static constexpr bool use_quantities = false;
static constexpr bool hasStressFreeExpansion = false;
static constexpr bool handlesThermalExpansion = false;
static constexpr unsigned short dimension = 0u;
static constexpr size_type material_properties_nb = 0;
static constexpr size_type internal_variables_nb  = 0;
static constexpr size_type external_variables_nb  = 0;
static constexpr size_type external_variables_nb2 = 0;
static constexpr bool hasConsistentTangentOperator = false;
static constexpr bool isConsistentTangentOperatorSymmetric = false;
static constexpr bool hasPredictionOperator = false;
static constexpr bool hasAPrioriTimeStepScalingFactor = false;
static constexpr bool hasComputeInternalEnergy = false;
static constexpr bool hasComputeDissipatedEnergy = false;
/*!
* \return the name of the class.
*/
static const char* getName(){
return "FullChabocheMemory";
}

};

/*!
* Partial specialisation for FullChabocheMemory.
*/
template<typename NumericType>
class MechanicalBehaviourTraits<FullChabocheMemory<ModellingHypothesis::PLANESTRESS, NumericType, false> >
{
using size_type = unsigned short;
public:
static constexpr bool is_defined = false;
static constexpr bool use_quantities = false;
static constexpr bool hasStressFreeExpansion = false;
static constexpr bool handlesThermalExpansion = false;
static constexpr unsigned short dimension = 0u;
static constexpr size_type material_properties_nb = 0;
static constexpr size_type internal_variables_nb  = 0;
static constexpr size_type external_variables_nb  = 0;
static constexpr size_type external_variables_nb2 = 0;
static constexpr bool hasConsistentTangentOperator = false;
static constexpr bool isConsistentTangentOperatorSymmetric = false;
static constexpr bool hasPredictionOperator = false;
static constexpr bool hasAPrioriTimeStepScalingFactor = false;
static constexpr bool hasComputeInternalEnergy = false;
static constexpr bool hasComputeDissipatedEnergy = false;
/*!
* \return the name of the class.
*/
static const char* getName(){
return "FullChabocheMemory";
}

};

} // end of namespace tfel::material

#endif /* LIB_TFELMATERIAL_FULLCHABOCHEMEMORY_HXX */
