/*!
* \file   TFEL/Material/LinearKinematicViscosity.hxx
* \brief  this file implements the LinearKinematicViscosity Behaviour.
*         File generated by tfel version 4.1.0
* \author Baris Telmen
 */

#ifndef LIB_TFELMATERIAL_LINEARKINEMATICVISCOSITY_HXX
#define LIB_TFELMATERIAL_LINEARKINEMATICVISCOSITY_HXX

#include<string>
#include<iostream>
#include<limits>
#include<stdexcept>
#include<algorithm>

#include"TFEL/Raise.hxx"
#include"TFEL/PhysicalConstants.hxx"
#include"TFEL/Config/TFELConfig.hxx"
#include"TFEL/Config/TFELTypes.hxx"
#include"TFEL/TypeTraits/IsFundamentalNumericType.hxx"
#include"TFEL/TypeTraits/IsReal.hxx"
#include"TFEL/Math/General/IEEE754.hxx"
#include"TFEL/Material/MaterialException.hxx"
#include"TFEL/Material/MechanicalBehaviour.hxx"
#include"TFEL/Material/MechanicalBehaviourTraits.hxx"
#include"TFEL/Material/OutOfBoundsPolicy.hxx"
#include"TFEL/Material/BoundsCheck.hxx"
#include"TFEL/Material/IsotropicPlasticity.hxx"
#include"TFEL/Material/Lame.hxx"
#include"TFEL/Material/Hosford1972YieldCriterion.hxx"
#include"MFront/BehaviourProfiler.hxx"
#include"TFEL/Material/LinearKinematicViscosityBehaviourData.hxx"
#include"TFEL/Material/LinearKinematicViscosityIntegrationData.hxx"

#include"TFEL/Math/Array/ViewsArray.hxx"
#include"TFEL/Math/tvector.hxx"
#include"TFEL/Math/Vector/tvectorIO.hxx"
#include"TFEL/Math/tmatrix.hxx"
#include"TFEL/Math/Matrix/tmatrixIO.hxx"
#include"TFEL/Math/st2tost2.hxx"
#include"TFEL/Math/ST2toST2/ST2toST2ConceptIO.hxx"
#include"TFEL/Math/TinyNewtonRaphsonSolver.hxx"
#include"MFront/Aster/Aster.hxx"

namespace tfel::material{

struct LinearKinematicViscosityParametersInitializer
{
static LinearKinematicViscosityParametersInitializer&
get();

double relative_value_for_the_equivalent_stress_lower_bound;
double theta;
double minimal_time_step_scaling_factor;
double maximal_time_step_scaling_factor;
double epsilon;
double numerical_jacobian_epsilon;
unsigned short iterMax;

void set(const char* const,const double);

void set(const char* const,const unsigned short);

/*!
 * \brief convert a string to double
 * \param[in] p : parameter
 * \param[in] v : value
 */
static double getDouble(const std::string&,const std::string&);
/*!
 * \brief convert a string to unsigned short
 * \param[in] p : parameter
 * \param[in] v : value
 */
static unsigned short getUnsignedShort(const std::string&,const std::string&);
private :

LinearKinematicViscosityParametersInitializer();

LinearKinematicViscosityParametersInitializer(const LinearKinematicViscosityParametersInitializer&);

LinearKinematicViscosityParametersInitializer&
operator=(const LinearKinematicViscosityParametersInitializer&);
/*!
 * \brief read the parameters from the given file
 * \param[out] pi : parameters initializer
 * \param[in]  fn : file name
 */
static void readParameters(LinearKinematicViscosityParametersInitializer&,const char* const);
};

//! \brief forward declaration
template<ModellingHypothesis::Hypothesis, typename NumericType, bool use_qt>
struct LinearKinematicViscosity;

//! \brief forward declaration
template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType>
std::ostream&
 operator <<(std::ostream&,const LinearKinematicViscosity<hypothesis, NumericType, false>&);

/*!
 * LinearKinematicViscosity profiler
 */
struct LinearKinematicViscosityProfiler
{
//! return the profiler associated with the behaviour
static mfront::BehaviourProfiler& getProfiler();
}; // end of struct LinearKinematicViscosityProfiler

/*!
* \class LinearKinematicViscosity
* \brief This class implements the LinearKinematicViscosity behaviour.
* \tparam hypothesis: modelling hypothesis.
* \tparam NumericType: numerical type.
* \author Baris Telmen
* Simple kinematic behavior with 
* viscosity addition 
*/
template<ModellingHypothesis::Hypothesis hypothesis,typename NumericType>
struct LinearKinematicViscosity<hypothesis, NumericType, false> final
: public MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>,
public LinearKinematicViscosityProfiler,
public LinearKinematicViscosityBehaviourData<hypothesis, NumericType, false>,
public LinearKinematicViscosityIntegrationData<hypothesis, NumericType, false>,
public tfel::math::TinyNewtonRaphsonSolver<2*ModellingHypothesisToStensorSize<hypothesis>::value+1, NumericType, LinearKinematicViscosity<hypothesis, NumericType, false>>{

static constexpr unsigned short N = ModellingHypothesisToSpaceDimension<hypothesis>::value;

static_assert(N==1||N==2||N==3);
static_assert(tfel::typetraits::IsFundamentalNumericType<NumericType>::cond);
static_assert(tfel::typetraits::IsReal<NumericType>::cond);

friend std::ostream& operator<< <>(std::ostream&,const LinearKinematicViscosity&);

friend struct tfel::math::TinyNonLinearSolverBase<2*ModellingHypothesisToStensorSize<hypothesis>::value+1, NumericType, LinearKinematicViscosity>;
static constexpr unsigned short TVectorSize = N;
typedef tfel::math::StensorDimeToSize<N> StensorDimeToSize;
static constexpr unsigned short StensorSize = StensorDimeToSize::value;
typedef tfel::math::TensorDimeToSize<N> TensorDimeToSize;
static constexpr unsigned short TensorSize = TensorDimeToSize::value;

using ushort =  unsigned short;
using Types = tfel::config::Types<N, NumericType, false>;
using Type = NumericType;
using numeric_type = typename Types::numeric_type;
using real = typename Types::real;
using time = typename Types::time;
using length = typename Types::length;
using frequency = typename Types::frequency;
using speed = typename Types::speed;
using stress = typename Types::stress;
using strain = typename Types::strain;
using strainrate = typename Types::strainrate;
using stressrate = typename Types::stressrate;
using temperature = typename Types::temperature;
using thermalexpansion = typename Types::thermalexpansion;
using thermalconductivity = typename Types::thermalconductivity;
using massdensity = typename Types::massdensity;
using energydensity = typename Types::energydensity;
using TVector = typename Types::TVector;
using DisplacementTVector = typename Types::DisplacementTVector;
using ForceTVector = typename Types::ForceTVector;
using HeatFlux = typename Types::HeatFlux;
using TemperatureGradient = typename Types::TemperatureGradient;
using Stensor = typename Types::Stensor;
using StressStensor = typename Types::StressStensor;
using StressRateStensor = typename Types::StressRateStensor;
using StrainStensor = typename Types::StrainStensor;
using StrainRateStensor = typename Types::StrainRateStensor;
using FrequencyStensor = typename Types::FrequencyStensor;
using Tensor = typename Types::Tensor;
using DeformationGradientTensor = typename Types::DeformationGradientTensor;
using DeformationGradientRateTensor = typename Types::DeformationGradientRateTensor;
using StressTensor = typename Types::StressTensor;
using StiffnessTensor = typename Types::StiffnessTensor;
using Stensor4 = typename Types::Stensor4;
using TangentOperator = StiffnessTensor;
using PhysicalConstants = tfel::PhysicalConstants<NumericType, false>;

public :

typedef LinearKinematicViscosityBehaviourData<hypothesis, NumericType, false> BehaviourData;
typedef LinearKinematicViscosityIntegrationData<hypothesis, NumericType, false> IntegrationData;
typedef typename MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::SMFlag SMFlag;
typedef typename MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::SMType SMType;
using MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::ELASTIC;
using MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::SECANTOPERATOR;
using MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::TANGENTOPERATOR;
using MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::CONSISTENTTANGENTOPERATOR;
using MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::NOSTIFFNESSREQUESTED;
using MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::STANDARDTANGENTOPERATOR;
using IntegrationResult = typename MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::IntegrationResult;

using MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::SUCCESS;
using MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::FAILURE;
using MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::UNRELIABLE_RESULTS;

using StressFreeExpansionType = StrainStensor;

private :



tfel::math::View<StrainStensor> deel;
#line 23 "LinearKinematicViscosity.mfront"
real& dp;
#line 25 "LinearKinematicViscosity.mfront"
tfel::math::View<StrainStensor> da;

#line 27 "LinearKinematicViscosity.mfront"
bool Fel;
struct{
stress lambda;
stress mu;
} sebdata;

real relative_value_for_the_equivalent_stress_lower_bound;
NumericType theta;
real minimal_time_step_scaling_factor;
real maximal_time_step_scaling_factor;
NumericType epsilon;
NumericType numerical_jacobian_epsilon;
ushort iterMax;

//! Tangent operator;
TangentOperator Dt;
//! alias to the tangent operator;
TangentOperator& dsig_ddeto;
// updating material properties, in mandatory
void updateMaterialPropertiesDependantOnStateVariables(){
using namespace std;
using namespace tfel::math;
using std::vector;
}

SMType stiffness_matrix_type;
void computeNumericalJacobian(tfel::math::tmatrix<2*StensorSize+1,2*StensorSize+1, NumericType>& njacobian)
{
using namespace std;
using namespace tfel::math;
tvector<2*StensorSize+1, NumericType> tzeros(this->zeros);
tvector<2*StensorSize+1, NumericType> tfzeros(this->fzeros);
tmatrix<2*StensorSize+1,2*StensorSize+1, NumericType> tjacobian(this->jacobian);
for(ushort mfront_idx = 0; mfront_idx != 2*StensorSize+1; ++mfront_idx){
this->zeros(mfront_idx) -= this->numerical_jacobian_epsilon;
this->computeThermodynamicForces();
this->computeFdF(true);
this->zeros = tzeros;
tvector<2*StensorSize+1, NumericType> tfzeros2(this->fzeros);
this->zeros(mfront_idx) += this->numerical_jacobian_epsilon;
this->computeThermodynamicForces();
this->computeFdF(true);
this->fzeros = (this->fzeros-tfzeros2) / (2 * (this->numerical_jacobian_epsilon));
for(ushort mfront_idx2 = 0; mfront_idx2!= 2*StensorSize+1; ++mfront_idx2){
njacobian(mfront_idx2,mfront_idx) = this->fzeros(mfront_idx2);
}
this->zeros    = tzeros;
this->fzeros   = tfzeros;
}
if(&njacobian!=&(this->jacobian)){
this->jacobian = tjacobian;
}
}

[[nodiscard]] bool
computePartialJacobianInvert(const tfel::math::TinyPermutation<2*StensorSize+1>& jacobian_permutation, tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_eel)
{
using namespace tfel::math;
for(ushort mfront_idx=0; mfront_idx !=StensorSize; ++mfront_idx){
tvector<2*StensorSize+1, NumericType> vect_e(NumericType(0));
vect_e(mfront_idx) = NumericType(1);
if(!TinyMatrixSolve<2*StensorSize+1, NumericType, false>::back_substitute(this->jacobian, jacobian_permutation, vect_e)){
return false;
}
for(ushort mfront_idx2=0; mfront_idx2!=StensorSize; ++mfront_idx2){
partial_jacobian_eel(mfront_idx2,mfront_idx)=vect_e(mfront_idx2);
}
}
return true;
}

[[nodiscard]] bool
computePartialJacobianInvert(const tfel::math::TinyPermutation<2*StensorSize+1>& jacobian_permutation, tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_eel,
tfel::math::derivative_type<strain, StrainStensor>& partial_jacobian_p)
{
using namespace tfel::math;
for(ushort mfront_idx=0; mfront_idx !=StensorSize; ++mfront_idx){
tvector<2*StensorSize+1, NumericType> vect_e(NumericType(0));
vect_e(mfront_idx) = NumericType(1);
if(!TinyMatrixSolve<2*StensorSize+1, NumericType, false>::back_substitute(this->jacobian, jacobian_permutation, vect_e)){
return false;
}
for(ushort mfront_idx2=0; mfront_idx2!=StensorSize; ++mfront_idx2){
partial_jacobian_eel(mfront_idx2,mfront_idx)=vect_e(mfront_idx2);
}
partial_jacobian_p(mfront_idx)=vect_e(StensorSize);
}
return true;
}

[[nodiscard]] bool
computePartialJacobianInvert(const tfel::math::TinyPermutation<2*StensorSize+1>& jacobian_permutation, tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_eel,
tfel::math::derivative_type<strain, StrainStensor>& partial_jacobian_p,
tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_a)
{
using namespace tfel::math;
for(ushort mfront_idx=0; mfront_idx !=StensorSize; ++mfront_idx){
tvector<2*StensorSize+1, NumericType> vect_e(NumericType(0));
vect_e(mfront_idx) = NumericType(1);
if(!TinyMatrixSolve<2*StensorSize+1, NumericType, false>::back_substitute(this->jacobian, jacobian_permutation, vect_e)){
return false;
}
for(ushort mfront_idx2=0; mfront_idx2!=StensorSize; ++mfront_idx2){
partial_jacobian_eel(mfront_idx2,mfront_idx)=vect_e(mfront_idx2);
}
partial_jacobian_p(mfront_idx)=vect_e(StensorSize);
for(ushort mfront_idx2=StensorSize+1; mfront_idx2!=2*StensorSize+1; ++mfront_idx2){
partial_jacobian_a(mfront_idx2,mfront_idx)=vect_e(mfront_idx2);
}
}
return true;
}

void computeThermodynamicForces(){
using namespace std;
using namespace tfel::math;
using std::vector;
{
mfront::BehaviourProfiler::Timer mfront_local_timer(LinearKinematicViscosityProfiler::getProfiler(),mfront::BehaviourProfiler::COMPUTETHERMODYNAMICFORCES);
this->sig = (this->sebdata.lambda)*trace(this->eel+(this->theta)*(this->deel))*Stensor::Id()+2*(this->sebdata.mu)*(this->eel+(this->theta)*(this->deel));
}

} // end of LinearKinematicViscosity::computeThermodynamicForces

void computeFinalThermodynamicForces(){
using namespace std;
using namespace tfel::math;
using std::vector;
{
mfront::BehaviourProfiler::Timer mfront_local_timer(LinearKinematicViscosityProfiler::getProfiler(),mfront::BehaviourProfiler::COMPUTEFINALTHERMODYNAMICFORCES);
this->sig = (this->sebdata.lambda)*trace(this->eel)*Stensor::Id()+2*(this->sebdata.mu)*this->eel;
}

} // end of LinearKinematicViscosity::computeFinalThermodynamicForces

/*!
* \brief Update internal variables at end of integration
*/
void updateIntegrationVariables(){
}

/*!
* \brief Update internal variables at end of integration
*/
void updateStateVariables(){
this->eel += this->deel;
this->p += this->dp;
this->a += this->da;
}

/*!
* \brief Update auxiliary state variables at end of integration
*/
void updateAuxiliaryStateVariables()
{}

//! \brief return an elastic prediction of the stresses
StressStensor computeElasticPrediction() const{
return this->sebdata.lambda*trace(this->eel+(this->theta)*(this->deto))*Stensor::Id()+2*(this->sebdata.mu)*(this->eel+(this->theta)*(this->deto));
}


//! \brief Default constructor (disabled)
LinearKinematicViscosity() =delete ;
//! \brief Copy constructor (disabled)
LinearKinematicViscosity(const LinearKinematicViscosity&) = delete;
//! \brief Assignement operator (disabled)
LinearKinematicViscosity& operator = (const LinearKinematicViscosity&) = delete;

public:

/*!
* \brief Constructor
*/
LinearKinematicViscosity(const LinearKinematicViscosityBehaviourData<hypothesis, NumericType, false>& src1,
const LinearKinematicViscosityIntegrationData<hypothesis, NumericType, false>& src2)
: LinearKinematicViscosityBehaviourData<hypothesis, NumericType, false>(src1),
LinearKinematicViscosityIntegrationData<hypothesis, NumericType, false>(src2),
deel(tfel::math::map<StrainStensor, 0>(this->zeros)),
dp(this->zeros(StensorSize)),
da(tfel::math::map<StrainStensor, StensorSize+1>(this->zeros)),
dsig_ddeto(Dt)
{
using namespace std;
using namespace tfel::math;
using std::vector;
this->relative_value_for_the_equivalent_stress_lower_bound = LinearKinematicViscosityParametersInitializer::get().relative_value_for_the_equivalent_stress_lower_bound;
this->theta = LinearKinematicViscosityParametersInitializer::get().theta;
this->minimal_time_step_scaling_factor = LinearKinematicViscosityParametersInitializer::get().minimal_time_step_scaling_factor;
this->maximal_time_step_scaling_factor = LinearKinematicViscosityParametersInitializer::get().maximal_time_step_scaling_factor;
this->epsilon = LinearKinematicViscosityParametersInitializer::get().epsilon;
this->numerical_jacobian_epsilon = LinearKinematicViscosityParametersInitializer::get().numerical_jacobian_epsilon;
this->iterMax = LinearKinematicViscosityParametersInitializer::get().iterMax;
}

/*
 * \brief constructor for the Aster interface
 * \param[in] ASTERdt_: time increment
 * \param[in] ASTERT_: temperature
 * \param[in] ASTERdT_: temperature increment
 * \param[in] ASTERmat: material properties
 * \param[in] ASTERint_vars: state variables
 * \param[in] ASTERext_vars: external state variables
 * \param[in] ASTERdext_vars: external state variables increments
 */
LinearKinematicViscosity(const NumericType* const ASTERdt_,
const NumericType* const ASTERT_,
const NumericType* const ASTERdT_,
const NumericType* const ASTERmat,
const NumericType* const ASTERint_vars,
const NumericType* const ASTERext_vars,
const NumericType* const ASTERdext_vars)
: LinearKinematicViscosityBehaviourData<hypothesis, NumericType,false>(ASTERT_,ASTERmat,
ASTERint_vars,ASTERext_vars),
LinearKinematicViscosityIntegrationData<hypothesis, NumericType,false>(ASTERdt_,ASTERdT_,ASTERdext_vars),
deel(tfel::math::map<StrainStensor, 0>(this->zeros)),
dp(this->zeros(StensorSize)),
da(tfel::math::map<StrainStensor, StensorSize+1>(this->zeros)),
dsig_ddeto(Dt)
{
using namespace std;
using namespace tfel::math;
using std::vector;
this->relative_value_for_the_equivalent_stress_lower_bound = LinearKinematicViscosityParametersInitializer::get().relative_value_for_the_equivalent_stress_lower_bound;
this->theta = LinearKinematicViscosityParametersInitializer::get().theta;
this->minimal_time_step_scaling_factor = LinearKinematicViscosityParametersInitializer::get().minimal_time_step_scaling_factor;
this->maximal_time_step_scaling_factor = LinearKinematicViscosityParametersInitializer::get().maximal_time_step_scaling_factor;
this->epsilon = LinearKinematicViscosityParametersInitializer::get().epsilon;
this->numerical_jacobian_epsilon = LinearKinematicViscosityParametersInitializer::get().numerical_jacobian_epsilon;
this->iterMax = LinearKinematicViscosityParametersInitializer::get().iterMax;
}

/*!
 * \ brief initialize the behaviour with user code
 */
[[nodiscard]] bool initialize(){
using namespace std;
using namespace tfel::math;
using std::vector;
{
mfront::BehaviourProfiler::Timer mfront_local_timer_binit(LinearKinematicViscosityProfiler::getProfiler(),mfront::BehaviourProfiler::BEFOREINITIALIZELOCALVARIABLES);
// initialisation Lame's coefficients
this->sebdata.lambda = tfel::material::computeLambda(this->young,this->nu);
this->sebdata.mu = tfel::material::computeMu(this->young,this->nu);

}
{
mfront::BehaviourProfiler::Timer mfront_local_timer_init(LinearKinematicViscosityProfiler::getProfiler(),mfront::BehaviourProfiler::INITIALIZELOCALVARIABLES);
#line 31 "LinearKinematicViscosity.mfront"
StressStensor scin = computeElasticPrediction();
#line 32 "LinearKinematicViscosity.mfront"
scin -= 2.*this->C*this->a/3.;
#line 33 "LinearKinematicViscosity.mfront"
const stress seq = sigmaeq(scin);
#line 34 "LinearKinematicViscosity.mfront"
this->Fel = seq > 0;
}
return true;
}

/*!
 * \brief set the policy for "out of bounds" conditions
 */
void
setOutOfBoundsPolicy(const OutOfBoundsPolicy policy_value){
  this->policy = policy_value;
} // end of setOutOfBoundsPolicy

/*!
* \return the modelling hypothesis
*/
constexpr ModellingHypothesis::Hypothesis
getModellingHypothesis() const{
return hypothesis;
} // end of getModellingHypothesis

//! \brief check physical bounds and standard bounds
void checkBounds() const{
} // end of checkBounds

[[nodiscard]] IntegrationResult
computePredictionOperator(const SMFlag smflag,const SMType smt) override{
using namespace std;
using namespace tfel::math;
using std::vector;
tfel::raise_if(smflag!=MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::STANDARDTANGENTOPERATOR,
"invalid prediction operator flag");
{
mfront::BehaviourProfiler::Timer mfront_local_timer(LinearKinematicViscosityProfiler::getProfiler(),mfront::BehaviourProfiler::COMPUTEPREDICTIONOPERATOR);
if((smt==ELASTIC)||(smt==SECANTOPERATOR)){
  computeAlteredElasticStiffness<hypothesis, stress>::exe(Dt,this->sebdata.lambda,this->sebdata.mu);
} else {
  return FAILURE;
}}
return SUCCESS;
}

real getMinimalTimeStepScalingFactor() const noexcept override{
  return this->minimal_time_step_scaling_factor;
}

std::pair<bool, real>
computeAPrioriTimeStepScalingFactor(const real current_time_step_scaling_factor) const override{
const auto time_scaling_factor = this->computeAPrioriTimeStepScalingFactorII();
return {time_scaling_factor.first,
        std::min(std::min(std::max(time_scaling_factor.second,
                                   this->minimal_time_step_scaling_factor),
                          this->maximal_time_step_scaling_factor),
                  current_time_step_scaling_factor)};
}

/*!
 * \brief Integrate behaviour law over the time step
 */
[[nodiscard]] IntegrationResult integrate(const SMFlag smflag,const SMType smt) override{
using namespace std;
using namespace tfel::math;
this->stiffness_matrix_type = smt;
tfel::raise_if(smflag!=MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::STANDARDTANGENTOPERATOR,
"invalid tangent operator flag");
{
mfront::BehaviourProfiler::Timer mfront_local_timer(LinearKinematicViscosityProfiler::getProfiler(),mfront::BehaviourProfiler::INTEGRATOR);
tfel::math::TinyNewtonRaphsonSolver<2*ModellingHypothesisToStensorSize<hypothesis>::value+1, NumericType, LinearKinematicViscosity<hypothesis, NumericType, false>>::epsilon = this->epsilon;
tfel::math::TinyNewtonRaphsonSolver<2*ModellingHypothesisToStensorSize<hypothesis>::value+1, NumericType, LinearKinematicViscosity<hypothesis, NumericType, false>>::iterMax = this->iterMax;
if(!this->solveNonLinearSystem()){
return MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::FAILURE;
}
if (this->stiffness_matrix_type != NOSTIFFNESSREQUESTED){
this->updateOrCheckJacobian();
}
}
this->updateIntegrationVariables();
this->updateStateVariables();
this->computeFinalThermodynamicForces();
this->updateAuxiliaryStateVariables();
if(smt!=NOSTIFFNESSREQUESTED){
if(!this->computeConsistentTangentOperator(smt)){
return MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::FAILURE;
}
}
return MechanicalBehaviour<MechanicalBehaviourBase::STANDARDSTRAINBASEDBEHAVIOUR,hypothesis, NumericType, false>::SUCCESS;
} // end of LinearKinematicViscosity::integrate

bool computeResidual(){
this->computeThermodynamicForces();
return this->computeFdF(false);
}
//! \return the norm of the residual
NumericType computeResidualNorm() {
return tfel::math::norm(this->fzeros) / (2*StensorSize+1);
}
/*!
 * \brief check the convergence of the method
 * \param[in] error: current error
 */
bool checkConvergence(const NumericType error) {
auto converged = error < this->epsilon;
return converged;
}
/*!
 * \brief update the jacobian matrix if required.
 * \param[in] converged: boolean stating if the method is
 * called after the convergence of the algorithm or before
 * the computation of the next correction.
 *
 * This method can be used to compute the jacobian or part
 * of the jacobian numerically. If the jacobian was computed
 * in `computeResidual`, this method can be used to compare it
 * to a numerical approximation.
 */
void updateOrCheckJacobian(){
}
/*!
 * \brief method meant to set bounds on some components
 * of the current Newton correction or to implement a line
 * search.
 */
void processNewCorrection()
{
}
/*!
 * \brief method meant to process the new estimate.
 *
 * This method may be called to apply bounds on the
 * new estimate and update material properties
 * dependending on the current state.
 */
void processNewEstimate(){
this->updateMaterialPropertiesDependantOnStateVariables();
}
/*!
 * \brief solve linear system
 * \return true on success
 * \param[in] m: matrix
 * \param[in,out] v: right hand side on input, solution on output
 */
bool solveLinearSystem(tfel::math::tmatrix<2*StensorSize+1, 2*StensorSize+1, NumericType>& mfront_matrix,tfel::math::tvector<2*StensorSize+1, NumericType>& mfront_vector)const noexcept{
auto mfront_success = true;
{
mfront::BehaviourProfiler::Timer mfront_local_timer_lu(LinearKinematicViscosityProfiler::getProfiler(),mfront::BehaviourProfiler::TINYMATRIXSOLVE);
mfront_success = tfel::math::TinyNewtonRaphsonSolver<2*ModellingHypothesisToStensorSize<hypothesis>::value+1, NumericType, LinearKinematicViscosity<hypothesis, NumericType, false>>::solveLinearSystem(mfront_matrix, mfront_vector);
}
return mfront_success;
}
/*!
* \brief compute fzeros and jacobian
*/
bool computeFdF(const bool perturbatedSystemEvaluation){
using namespace std;
using namespace tfel::math;
using std::vector;
mfront::BehaviourProfiler::Timer mfront_local_timer(LinearKinematicViscosityProfiler::getProfiler(),mfront::BehaviourProfiler::COMPUTEFDF);
// silent compiler warning
static_cast<void>(perturbatedSystemEvaluation); 
constexpr auto eel_offset = 0;
constexpr auto p_offset = StensorSize;
constexpr auto a_offset = StensorSize+1;
auto feel = tfel::math::map<StrainStensor, 0>(this->fzeros);
real& fp(this->fzeros(StensorSize));
auto fa = tfel::math::map<StrainStensor, StensorSize+1>(this->fzeros);
// derivative of residual feel with respect to variable eel
auto&& dfeel_ddeel = tfel::math::map_derivative<0, 0, StrainStensor, StrainStensor>(this->jacobian);
// derivative of residual feel with respect to variable p
auto&& dfeel_ddp = tfel::math::map_derivative<0, StensorSize, StrainStensor, strain>(this->jacobian);
// derivative of residual feel with respect to variable a
auto&& dfeel_dda = tfel::math::map_derivative<0, StensorSize+1, StrainStensor, StrainStensor>(this->jacobian);
// derivative of residual fp with respect to variable eel
auto&& dfp_ddeel = tfel::math::map_derivative<StensorSize, 0, strain, StrainStensor>(this->jacobian);
// derivative of residual fp with respect to variable p
auto&& dfp_ddp = tfel::math::map_derivative<StensorSize, StensorSize, strain, strain>(this->jacobian);
// derivative of residual fp with respect to variable a
auto&& dfp_dda = tfel::math::map_derivative<StensorSize, StensorSize+1, strain, StrainStensor>(this->jacobian);
// derivative of residual fa with respect to variable eel
auto&& dfa_ddeel = tfel::math::map_derivative<StensorSize+1, 0, StrainStensor, StrainStensor>(this->jacobian);
// derivative of residual fa with respect to variable p
auto&& dfa_ddp = tfel::math::map_derivative<StensorSize+1, StensorSize, StrainStensor, strain>(this->jacobian);
// derivative of residual fa with respect to variable a
auto&& dfa_dda = tfel::math::map_derivative<StensorSize+1, StensorSize+1, StrainStensor, StrainStensor>(this->jacobian);
// setting jacobian to identity
std::fill(this->jacobian.begin(),this->jacobian.end(), NumericType(0));
for(ushort mfront_idx = 0; mfront_idx != 2*StensorSize+1; ++mfront_idx){
this->jacobian(mfront_idx, mfront_idx) = NumericType(1);
}
// setting f values to zeros
this->fzeros = this->zeros;
feel -= this->deto;
#line 38 "LinearKinematicViscosity.mfront"
constexpr const real eps = 1.e-12;
#line 39 "LinearKinematicViscosity.mfront"
if ((this->Fel))
#line 40 "LinearKinematicViscosity.mfront"
{
#line 41 "LinearKinematicViscosity.mfront"
const auto mu       =   computeMu((this->young),(this->nu));
#line 42 "LinearKinematicViscosity.mfront"
StressStensor scin  =   (this->sig);
#line 43 "LinearKinematicViscosity.mfront"
StrainStensor a_    =   (this->a) + theta*(this->da);
#line 44 "LinearKinematicViscosity.mfront"
scin               -=   2.*(this->C)*a_/3.;
#line 45 "LinearKinematicViscosity.mfront"
const stress seq    =   sigmaeq(scin);
#line 47 "LinearKinematicViscosity.mfront"
const stress F      =   max(seq, stress(0));
#line 48 "LinearKinematicViscosity.mfront"
const real Fexp     =   pow(F/(this->K),(this->m)-1)/(this->K);
#line 49 "LinearKinematicViscosity.mfront"
const auto iseq     =   1/max(seq,eps*(this->young));
#line 51 "LinearKinematicViscosity.mfront"
const Stensor n     =   3*deviator(scin)*iseq/2.;
#line 53 "LinearKinematicViscosity.mfront"
const Stensor4 Jmn  =   Stensor4::M() - (n^n);
#line 54 "LinearKinematicViscosity.mfront"
const auto vp       =   Fexp*F;
#line 56 "LinearKinematicViscosity.mfront"
feel               +=   (this->dp)*n;
#line 57 "LinearKinematicViscosity.mfront"
fp                 -=   vp * (this->dt);
#line 58 "LinearKinematicViscosity.mfront"
fa                  =   (this->da) - (this->dp)*n;
#line 60 "LinearKinematicViscosity.mfront"
dfeel_ddeel        +=   2*mu*theta*(this->dp)*Jmn*iseq ;
#line 61 "LinearKinematicViscosity.mfront"
dfeel_ddp           =   n;
#line 62 "LinearKinematicViscosity.mfront"
dfeel_dda            =   -2*(this->C)*(this->dp)*theta*iseq*Jmn/3.;
#line 64 "LinearKinematicViscosity.mfront"
dfp_ddp             =   1.;
#line 65 "LinearKinematicViscosity.mfront"
dfp_ddeel           =  - 2*Fexp*(this->m)*(this->dt)* 2.*mu*theta*(n|Stensor4::M())/3.;
#line 66 "LinearKinematicViscosity.mfront"
dfp_dda             =   2*Fexp*(this->m)*(this->dt)*(this->C)*theta/3.*n;
#line 68 "LinearKinematicViscosity.mfront"
dfa_ddeel           =   -2*mu*theta*(this->dp)*Jmn *iseq;
#line 69 "LinearKinematicViscosity.mfront"
dfa_ddp             =   -n;
#line 70 "LinearKinematicViscosity.mfront"
dfa_dda             =   Stensor4::Id() + 2*(this->C)/3.*(this->dp)*theta*iseq*Jmn;
#line 72 "LinearKinematicViscosity.mfront"
}
static_cast<void>(dfeel_ddeel); /* suppress potential warnings */
static_cast<void>(dfeel_ddp); /* suppress potential warnings */
static_cast<void>(dfeel_dda); /* suppress potential warnings */
static_cast<void>(dfp_ddeel); /* suppress potential warnings */
static_cast<void>(dfp_ddp); /* suppress potential warnings */
static_cast<void>(dfp_dda); /* suppress potential warnings */
static_cast<void>(dfa_ddeel); /* suppress potential warnings */
static_cast<void>(dfa_ddp); /* suppress potential warnings */
static_cast<void>(dfa_dda); /* suppress potential warnings */
static_cast<void>(eel_offset);
static_cast<void>(p_offset);
static_cast<void>(a_offset);
return true;
}

std::pair<bool, real>
computeAPosterioriTimeStepScalingFactor(const real current_time_step_scaling_factor) const override{
const auto time_scaling_factor = this->computeAPosterioriTimeStepScalingFactorII();
return {time_scaling_factor.first,
        std::min(std::min(std::max(time_scaling_factor.second,
                                   this->minimal_time_step_scaling_factor),
                          this->maximal_time_step_scaling_factor),
                 current_time_step_scaling_factor)};
}

/*!
* \brief Update the internal energy at end of the time step
* \param[in] Psi_s: internal energy at end of the time step
*/
void computeInternalEnergy(stress& Psi_s) const
{
Psi_s=stress{0};
}

/*!
* \brief Update the dissipated energy at end of the time step
* \param[in] Psi_d: dissipated energy at end of the time step
*/
void computeDissipatedEnergy(stress& Psi_d) const
{
Psi_d=stress{0};
}

bool computeConsistentTangentOperator(const SMType smt){
using namespace std;
using namespace tfel::math;
using std::vector;
auto mfront_success = true;
TinyPermutation<2*StensorSize+1> jacobian_permutation;
if(!TinyMatrixSolve<2*StensorSize+1, NumericType, false>::decomp(this->jacobian,jacobian_permutation)){
return false;
}
struct TFEL_VISIBILITY_LOCAL GetPartialJacobianInvert{
GetPartialJacobianInvert(LinearKinematicViscosity& mfront_behaviour_argument,
const tfel::math::TinyPermutation<2*StensorSize+1>& mfront_permutation_argument,
bool& mfront_success_argument)
: mfront_get_partial_jacobian_invert_behaviour(mfront_behaviour_argument),
mfront_get_partial_jacobian_invert_permutation(mfront_permutation_argument),
mfront_success_reference(mfront_success_argument){}
void operator()(tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_eel){
if(!this->mfront_get_partial_jacobian_invert_behaviour.computePartialJacobianInvert(this->mfront_get_partial_jacobian_invert_permutation, partial_jacobian_eel)){
this->mfront_success_reference = false;
}
}
void operator()(tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_eel,
tfel::math::derivative_type<strain, StrainStensor>& partial_jacobian_p){
if(!this->mfront_get_partial_jacobian_invert_behaviour.computePartialJacobianInvert(this->mfront_get_partial_jacobian_invert_permutation, partial_jacobian_eel,
partial_jacobian_p)){
this->mfront_success_reference = false;
}
}
void operator()(tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_eel,
tfel::math::derivative_type<strain, StrainStensor>& partial_jacobian_p,
tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_a){
if(!this->mfront_get_partial_jacobian_invert_behaviour.computePartialJacobianInvert(this->mfront_get_partial_jacobian_invert_permutation, partial_jacobian_eel,
partial_jacobian_p,
partial_jacobian_a)){
this->mfront_success_reference = false;
}
}
private:
LinearKinematicViscosity& mfront_get_partial_jacobian_invert_behaviour;
const tfel::math::TinyPermutation<2*StensorSize+1>& mfront_get_partial_jacobian_invert_permutation;
bool& mfront_success_reference;
}; // end of struct GetPartialJacobianInvert
GetPartialJacobianInvert getPartialJacobianInvert(*this, jacobian_permutation, mfront_success);
{
mfront::BehaviourProfiler::Timer mfront_local_timer(LinearKinematicViscosityProfiler::getProfiler(),mfront::BehaviourProfiler::COMPUTETANGENTOPERATOR);
if((smt==ELASTIC)||(smt==SECANTOPERATOR)){
computeAlteredElasticStiffness<hypothesis, stress>::exe(Dt,this->sebdata.lambda,this->sebdata.mu);
} else if (smt==CONSISTENTTANGENTOPERATOR){
StiffnessTensor Hooke;
Stensor4 Je;
computeElasticStiffness<N, stress>::exe(Hooke,this->sebdata.lambda,this->sebdata.mu);
getPartialJacobianInvert(Je);
Dt = Hooke*Je;
} else {
  return false;
}}

return mfront_success;
}

/*!
* \brief compute the sound velocity
* \param[in] rho_m0: mass density in the reference configuration
*/
speed computeSpeedOfSound(const massdensity&) const {
return speed(0);

}

const TangentOperator& getTangentOperator() const{
return this->Dt;
}

void updateExternalStateVariables(){
this->eto  += this->deto;
this->T += this->dT;
}

//!
~LinearKinematicViscosity()
 override = default;

private:

std::pair<bool, real> computeAPrioriTimeStepScalingFactorII() const{
return {true, this->maximal_time_step_scaling_factor};
}

std::pair<bool, real> computeAPosterioriTimeStepScalingFactorII() const{
return {true,this->maximal_time_step_scaling_factor};
}

//! policy for treating out of bounds conditions
OutOfBoundsPolicy policy = tfel::material::None;

}; // end of LinearKinematicViscosity class

template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType>
std::ostream&
operator <<(std::ostream& os,const LinearKinematicViscosity<hypothesis, NumericType, false>& b)
{
os << "εᵗᵒ : " << b.eto << '\n';
os << "Δεᵗᵒ : " << b.deto << '\n';
os << "σ : " << b.sig << '\n';
os << "Δt : " << b.dt << '\n';
os << "young : " << b.young << '\n';
os << "nu : " << b.nu << '\n';
os << "C : " << b.C << '\n';
os << "K : " << b.K << '\n';
os << "m : " << b.m << '\n';
os << "εᵉˡ : " << b.eel << '\n';
os << "Δεᵉˡ : " << b.deel << '\n';
os << "p : " << b.p << '\n';
os << "Δp : " << b.dp << '\n';
os << "a : " << b.a << '\n';
os << "Δa : " << b.da << '\n';
os << "T : " << b.T << '\n';
os << "ΔT : " << b.dT << '\n';
os << "relative_value_for_the_equivalent_stress_lower_bound : " << b.relative_value_for_the_equivalent_stress_lower_bound << '\n';
os << "θ : " << b.theta << '\n';
os << "minimal_time_step_scaling_factor : " << b.minimal_time_step_scaling_factor << '\n';
os << "maximal_time_step_scaling_factor : " << b.maximal_time_step_scaling_factor << '\n';
os << "ε : " << b.epsilon << '\n';
os << "numerical_jacobian_epsilon : " << b.numerical_jacobian_epsilon << '\n';
os << "iterMax : " << b.iterMax << '\n';
return os;
}

/*!
* Partial specialisation for LinearKinematicViscosity.
*/
template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType>
class MechanicalBehaviourTraits<LinearKinematicViscosity<hypothesis, NumericType, false> >
{
using size_type = unsigned short;
static constexpr unsigned short N = ModellingHypothesisToSpaceDimension<hypothesis>::value;
static constexpr unsigned short TVectorSize = N;
typedef tfel::math::StensorDimeToSize<N> StensorDimeToSize;
static constexpr unsigned short StensorSize = StensorDimeToSize::value;
typedef tfel::math::TensorDimeToSize<N> TensorDimeToSize;
static constexpr unsigned short TensorSize = TensorDimeToSize::value;
public:
static constexpr bool is_defined = true;
static constexpr bool use_quantities = false;
static constexpr bool hasStressFreeExpansion = false;
static constexpr bool handlesThermalExpansion = false;
static constexpr unsigned short dimension = N;
static constexpr size_type material_properties_nb = 5;
static constexpr size_type internal_variables_nb  = 2*StensorSize+1;
static constexpr size_type external_variables_nb  = 1;
static constexpr size_type external_variables_nb2 = 0;
static constexpr bool hasConsistentTangentOperator = true;
static constexpr bool isConsistentTangentOperatorSymmetric = false;
static constexpr bool hasPredictionOperator = true;
static constexpr bool hasAPrioriTimeStepScalingFactor = false;
static constexpr bool hasComputeInternalEnergy = false;
static constexpr bool hasComputeDissipatedEnergy = false;
/*!
* \return the name of the class.
*/
static const char* getName(){
return "LinearKinematicViscosity";
}

};

/*!
* Partial specialisation for LinearKinematicViscosity.
*/
template<typename NumericType>
class MechanicalBehaviourTraits<LinearKinematicViscosity<ModellingHypothesis::AXISYMMETRICALGENERALISEDPLANESTRESS, NumericType, false> >
{
using size_type = unsigned short;
public:
static constexpr bool is_defined = false;
static constexpr bool use_quantities = false;
static constexpr bool hasStressFreeExpansion = false;
static constexpr bool handlesThermalExpansion = false;
static constexpr unsigned short dimension = 0u;
static constexpr size_type material_properties_nb = 0;
static constexpr size_type internal_variables_nb  = 0;
static constexpr size_type external_variables_nb  = 0;
static constexpr size_type external_variables_nb2 = 0;
static constexpr bool hasConsistentTangentOperator = false;
static constexpr bool isConsistentTangentOperatorSymmetric = false;
static constexpr bool hasPredictionOperator = false;
static constexpr bool hasAPrioriTimeStepScalingFactor = false;
static constexpr bool hasComputeInternalEnergy = false;
static constexpr bool hasComputeDissipatedEnergy = false;
/*!
* \return the name of the class.
*/
static const char* getName(){
return "LinearKinematicViscosity";
}

};

/*!
* Partial specialisation for LinearKinematicViscosity.
*/
template<typename NumericType>
class MechanicalBehaviourTraits<LinearKinematicViscosity<ModellingHypothesis::PLANESTRESS, NumericType, false> >
{
using size_type = unsigned short;
public:
static constexpr bool is_defined = false;
static constexpr bool use_quantities = false;
static constexpr bool hasStressFreeExpansion = false;
static constexpr bool handlesThermalExpansion = false;
static constexpr unsigned short dimension = 0u;
static constexpr size_type material_properties_nb = 0;
static constexpr size_type internal_variables_nb  = 0;
static constexpr size_type external_variables_nb  = 0;
static constexpr size_type external_variables_nb2 = 0;
static constexpr bool hasConsistentTangentOperator = false;
static constexpr bool isConsistentTangentOperatorSymmetric = false;
static constexpr bool hasPredictionOperator = false;
static constexpr bool hasAPrioriTimeStepScalingFactor = false;
static constexpr bool hasComputeInternalEnergy = false;
static constexpr bool hasComputeDissipatedEnergy = false;
/*!
* \return the name of the class.
*/
static const char* getName(){
return "LinearKinematicViscosity";
}

};

} // end of namespace tfel::material

#endif /* LIB_TFELMATERIAL_LINEARKINEMATICVISCOSITY_HXX */
