/*!
* \file   TFEL/Material/NonLinearIsotropicNonLinearKinematicBehaviourData.hxx
* \brief  this file implements the NonLinearIsotropicNonLinearKinematicBehaviourData class.
*         File generated by tfel version 4.1.0
 */

#ifndef LIB_TFELMATERIAL_NONLINEARISOTROPICNONLINEARKINEMATIC_BEHAVIOUR_DATA_HXX
#define LIB_TFELMATERIAL_NONLINEARISOTROPICNONLINEARKINEMATIC_BEHAVIOUR_DATA_HXX

#include<limits>
#include<string>
#include<sstream>
#include<iostream>
#include<stdexcept>
#include<algorithm>

#include"TFEL/Raise.hxx"
#include"TFEL/PhysicalConstants.hxx"
#include"TFEL/Config/TFELConfig.hxx"
#include"TFEL/Config/TFELTypes.hxx"
#include"TFEL/TypeTraits/IsFundamentalNumericType.hxx"
#include"TFEL/TypeTraits/IsReal.hxx"
#include"TFEL/Math/General/Abs.hxx"
#include"TFEL/Math/General/IEEE754.hxx"
#include"TFEL/Math/Array/ViewsArrayIO.hxx"
#include"TFEL/Math/Array/fsarrayIO.hxx"
#include"TFEL/Math/Array/runtime_arrayIO.hxx"
#include"TFEL/Math/fsarray.hxx"
#include"TFEL/Math/runtime_array.hxx"
#include"TFEL/Math/tvector.hxx"
#include"TFEL/Math/Vector/tvectorIO.hxx"
#include"TFEL/Math/tmatrix.hxx"
#include"TFEL/Math/Matrix/tmatrixIO.hxx"
#include"TFEL/Math/stensor.hxx"
#include"TFEL/Math/Stensor/StensorConceptIO.hxx"
#include"TFEL/Math/st2tost2.hxx"
#include"TFEL/Math/ST2toST2/ST2toST2ConceptIO.hxx"
#include"TFEL/Material/ModellingHypothesis.hxx"

#include"MFront/Aster/Aster.hxx"

namespace tfel::material{

//! \brief forward declaration
template<ModellingHypothesis::Hypothesis hypothesis,typename,bool>
class NonLinearIsotropicNonLinearKinematicBehaviourData;

//! \brief forward declaration
template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType,bool use_qt>
class NonLinearIsotropicNonLinearKinematicIntegrationData;

//! \brief forward declaration
template<ModellingHypothesis::Hypothesis hypothesis,typename NumericType>
std::ostream&
 operator <<(std::ostream&,const NonLinearIsotropicNonLinearKinematicBehaviourData<hypothesis, NumericType,false>&);

template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType>
class NonLinearIsotropicNonLinearKinematicBehaviourData<hypothesis, NumericType,false>
{

static constexpr unsigned short N = ModellingHypothesisToSpaceDimension<hypothesis>::value;
static_assert(N==1||N==2||N==3);
static_assert(tfel::typetraits::IsFundamentalNumericType<NumericType>::cond);
static_assert(tfel::typetraits::IsReal<NumericType>::cond);

friend std::ostream& operator<< <>(std::ostream&,const NonLinearIsotropicNonLinearKinematicBehaviourData&);

/* integration data is declared friend to access   driving variables at the beginning of the time step */
friend class NonLinearIsotropicNonLinearKinematicIntegrationData<hypothesis, NumericType, false>;

static constexpr unsigned short TVectorSize = N;
using StensorDimeToSize = tfel::math::StensorDimeToSize<N>;
static constexpr unsigned short StensorSize = StensorDimeToSize::value;
using TensorDimeToSize = tfel::math::TensorDimeToSize<N>;
static constexpr unsigned short TensorSize = TensorDimeToSize::value;

using ushort =  unsigned short;
using Types = tfel::config::Types<N, NumericType, false>;
using Type = NumericType;
using numeric_type = typename Types::numeric_type;
using real = typename Types::real;
using time = typename Types::time;
using length = typename Types::length;
using frequency = typename Types::frequency;
using speed = typename Types::speed;
using stress = typename Types::stress;
using strain = typename Types::strain;
using strainrate = typename Types::strainrate;
using stressrate = typename Types::stressrate;
using temperature = typename Types::temperature;
using thermalexpansion = typename Types::thermalexpansion;
using thermalconductivity = typename Types::thermalconductivity;
using massdensity = typename Types::massdensity;
using energydensity = typename Types::energydensity;
using TVector = typename Types::TVector;
using DisplacementTVector = typename Types::DisplacementTVector;
using ForceTVector = typename Types::ForceTVector;
using HeatFlux = typename Types::HeatFlux;
using TemperatureGradient = typename Types::TemperatureGradient;
using Stensor = typename Types::Stensor;
using StressStensor = typename Types::StressStensor;
using StressRateStensor = typename Types::StressRateStensor;
using StrainStensor = typename Types::StrainStensor;
using StrainRateStensor = typename Types::StrainRateStensor;
using FrequencyStensor = typename Types::FrequencyStensor;
using Tensor = typename Types::Tensor;
using DeformationGradientTensor = typename Types::DeformationGradientTensor;
using DeformationGradientRateTensor = typename Types::DeformationGradientRateTensor;
using StressTensor = typename Types::StressTensor;
using StiffnessTensor = typename Types::StiffnessTensor;
using Stensor4 = typename Types::Stensor4;
using TangentOperator = StiffnessTensor;
using PhysicalConstants = tfel::PhysicalConstants<NumericType, false>;

protected:

StrainStensor eto;

StressStensor sig;

#line 6 "NonLinearIsotropicNonLinearKinematic.mfront"
stress young;
#line 8 "NonLinearIsotropicNonLinearKinematic.mfront"
real nu;
#line 10 "NonLinearIsotropicNonLinearKinematic.mfront"
real R_inf;
#line 11 "NonLinearIsotropicNonLinearKinematic.mfront"
real R_0;
#line 12 "NonLinearIsotropicNonLinearKinematic.mfront"
real b;
#line 13 "NonLinearIsotropicNonLinearKinematic.mfront"
tfel::math::fsarray<2, real > C;
#line 14 "NonLinearIsotropicNonLinearKinematic.mfront"
tfel::math::fsarray<2, real > g;

StrainStensor eel;
#line 16 "NonLinearIsotropicNonLinearKinematic.mfront"
real p;
#line 17 "NonLinearIsotropicNonLinearKinematic.mfront"
tfel::math::fsarray<2, Stensor > a;
temperature T;

public:

/*!
* \brief Default constructor
*/
NonLinearIsotropicNonLinearKinematicBehaviourData()
{}

/*!
* \brief copy constructor
*/
NonLinearIsotropicNonLinearKinematicBehaviourData(const NonLinearIsotropicNonLinearKinematicBehaviourData& src)
: eto(src.eto),
sig(src.sig),
young(src.young),
nu(src.nu),
R_inf(src.R_inf),
R_0(src.R_0),
b(src.b),
C(src.C),
g(src.g),
eel(src.eel),
p(src.p),
a(src.a),
T(src.T)
{}

/*
 * \brief constructor for the Aster interface
 * \param[in] ASTERT_: temperature
 * \param[in] ASTERmat: material properties
 * \param[in] ASTERint_vars: state variables
 * \param[in] ASTERext_vars: external std::ate variables
 */
NonLinearIsotropicNonLinearKinematicBehaviourData(const NumericType* const ASTERT_,const NumericType* const ASTERmat,
const NumericType* const ASTERint_vars
,const NumericType* const)
: young(ASTERmat[0-0]),
nu(ASTERmat[1-0]),
R_inf(ASTERmat[2-0]),
R_0(ASTERmat[3-0]),
b(ASTERmat[4-0]),
eel(&ASTERint_vars[0]),
p(ASTERint_vars[StensorSize]),
T(*ASTERT_)
{
C[0] = ASTERmat[5];
C[1] = ASTERmat[6];
g[0] = ASTERmat[7];
g[1] = ASTERmat[8];
a[0].import(&ASTERint_vars[StensorSize+1]);
a[1].import(&ASTERint_vars[2*StensorSize+1]);
}

void setASTERBehaviourDataGradients(const NumericType* const ASTERstran)
{
this->eto.importVoigt(ASTERstran);
}

void setASTERBehaviourDataThermodynamicForces(const NumericType* const ASTERstress_)
{
this->sig.importTab(ASTERstress_);
}


/*
* \brief Assignement operator
*/
NonLinearIsotropicNonLinearKinematicBehaviourData&
operator=(const NonLinearIsotropicNonLinearKinematicBehaviourData& src){
this->eto = src.eto;
this->sig = src.sig;
this->young = src.young;
this->nu = src.nu;
this->R_inf = src.R_inf;
this->R_0 = src.R_0;
this->b = src.b;
this->C = src.C;
this->g = src.g;
this->eel = src.eel;
this->p = src.p;
this->a = src.a;
this->T = src.T;
return *this;
}

void
ASTERexportStateData(NumericType * const ASTERstress_, NumericType * const ASTERstatev) const
{
using namespace tfel::math;
this->sig.exportTab(ASTERstress_);
exportToBaseTypeArray(this->eel,&ASTERstatev[0]);
ASTERstatev[StensorSize] = this->p;
exportToBaseTypeArray(this->a[0],&ASTERstatev[StensorSize+1]);
exportToBaseTypeArray(this->a[1],&ASTERstatev[2*StensorSize+1]);
} // end of ASTERexportStateData

}; // end of NonLinearIsotropicNonLinearKinematicBehaviourDataclass

template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType>
std::ostream&
operator <<(std::ostream& os,const NonLinearIsotropicNonLinearKinematicBehaviourData<hypothesis, NumericType, false>& b)
{
os << "εᵗᵒ : " << b.eto << '\n';
os << "σ : " << b.sig << '\n';
os << "young : " << b.young << '\n';
os << "nu : " << b.nu << '\n';
os << "R_inf : " << b.R_inf << '\n';
os << "R_0 : " << b.R_0 << '\n';
os << "b : " << b.b << '\n';
os << "C : " << b.C << '\n';
os << "g : " << b.g << '\n';
os << "εᵉˡ : " << b.eel << '\n';
os << "p : " << b.p << '\n';
os << "a : " << b.a << '\n';
os << "T : " << b.T << '\n';
return os;
}

} // end of namespace tfel::material

#endif /* LIB_TFELMATERIAL_NONLINEARISOTROPICNONLINEARKINEMATIC_BEHAVIOUR_DATA_HXX */
